# Generated by Django 3.1.7 on 2022-01-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailAction',
        ),
    ]
