# Generated by Django 3.1.7 on 2022-01-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20220123_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='KeyValue',
        ),
    ]
