# Generated by Django 3.1.7 on 2022-01-18 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=20)),
                ('last_four', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('stripe_id', models.CharField(max_length=50)),
                ('max_submissions', models.IntegerField(default=100)),
                ('allow_webhooks', models.BooleanField(default=True)),
                ('allow_notification', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_recaptchs', models.BooleanField(default=True)),
                ('allow_uploads', models.BooleanField(default=True)),
                ('upload_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], max_length=1)),
                ('message', models.CharField(max_length=100)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
