# Generated by Django 3.1.7 on 2022-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_submissions',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='upload_limit',
            field=models.IntegerField(default=0),
        ),
    ]
