# Generated by Django 3.1.7 on 2022-02-01 17:38

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20220201_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[forms.models.url_validator]),
        ),
    ]
